appName: starter-template
logger:
  pinoHttp:
    level: info
    redact:
      paths:
        __name: LOGGER_REDACT_JSON
        __format: json
      censor: '***'
port: 3000
database:
  options:
    username: DB_USER
    password: DB_PASS
    host: DB_HOST
    port: DB_PORT
    database: DB_NAME
cache:
  redis:
    host: REDIS_HOST
    port: REDIS_PORT
    username: REDIS_USER
    password: REDIS_PASS
  defaults:
    ttl: CACHE_TTL
  ttl:
    oauth_state: OAUTH_STATE_TTL
    access_token: OAUTH_ACCESS_TOKEN_TTL
    refresh_token: OAUTH_REFRESH_TOKEN_TTL
aws:
  region: AWS_REGION
  accessKeyId: AWS_ACCESS_KEY_ID
  secretAccessKey: AWS_SECRET_ACCESS_KEY
  s3:
    bucket: AWS_S3_BUCKET
platforms:
  facebook:
    clientId: FACEBOOK_CLIENT_ID
    clientSecret: FACEBOOK_CLIENT_SECRET
    redirectUri: FACEBOOK_REDIRECT_URI
    apiVersion: FACEBOOK_API_VERSION
