appName: starter-template
logger:
  pinoHttp:
    level: info
    redact:
      paths:
        __name: LOGGER_REDACT_JSON
        __format: json
      censor: '***'
port: 3000
database:
  options:
    user: DB_USER
    password: DB_PASS
    host: DB_HOST
    port: DB_PORT
    database: DB_NAME
