appName: starter-template
logger:
  pinoHttp:
    level: info
    redact:
      paths:
        __name: LOGGER_REDACT_JSON
        __format: json
      censor: '***'
port: 3000
database:
  options:
    user: DB_USER
    password: DB_PASS
    host: DB_HOST
    port: DB_PORT
    database: DB_NAME
cache:
  redis:
    host: localhost
    port: 6379
    username: redisuser 
    password: redispassword  
    # database: 0  # Optional - specific Redis database number
    # tls: false  # Optional - set to true for SSL/TLS connections  
  defaults:
    ttl: 14400  # Default TTL in seconds (4 hours)  
  ttl:
    oauth_state: 600  # 10 minutes for OAuth states
    access_token: 3600  # 1 hour for access tokens
    refresh_token: 604800  # 7 days for refresh tokens