appName: starter-template
logger:
  pinoHttp:
    level: info
    transport:
      target: pino-pretty
    redact:
      paths:
      - req.headers.authorization
      - req.headers.auth
      censor: '***'
port: 3000
clerk:
  clerkPublicKey: ""
messaging:
  throttle:
    messageRateMs: 500 # Time between messages (ms)
    typingRateMs: 2000 # Time between typing indicators (ms)
    readReceiptRateMs: 1000 # Time between read receipts (ms)
    maxClientsPerUser: 5 # Maximum number of concurrent connections per user
    connectionTimeout: 30000 # WebSocket connection timeout (ms)
db:
  options:
    type: postgres
    username: root
    password: admin
    host: postgres
    port: 5434
    database: luftsocial
    synchronize: true
cache:
  redis:
    host: redis
    port: 6379
    username: "" # Optional
    password: ${REDIS_PASSWORD} # Optional
    database: 0 # Optional - specific Redis database number
    tls: false # Optional - set to true for SSL/TLS connections  
  defaults:
    ttl: 14400 # Default TTL in seconds (4 hours)  
  ttl:
    oauth_state: 600 # 10 minutes for OAuth states
    access_token: 3600 # 1 hour for access tokens
    refresh_token: 604800 # 7 days for refresh tokens
aws:
  region: eu-central-1
  accessKeyId:
  secretAccessKey:
  s3:
    bucket: uploads-123-456
platforms:
  facebook:
    clientId: ${FACEBOOK_CLIENT_ID}
    clientSecret: ${FACEBOOK_CLIENT_SECRET}
    redirectUri: ${FACEBOOK_REDIRECT_URI}
    apiVersion: v22.0
  instagram:
    clientId: INSTAGRAM_CLIENT_ID
    clientSecret: INSTAGRAM_CLIENT_SECRET
    redirectUri: INSTAGRAM_REDIRECT_URI
    apiVersion: INSTAGRAM_API_VERSION
  linkedin:
    clientId: LINKEDIN_CLIENT_ID
    clientSecret: LINKEDIN_CLIENT_SECRET
    redirectUri: LINKEDIN_REDIRECT_URI
    apiVersion: LINKEDIN_API_VERSION
  tiktok:
    clientKey: TIKTOK_CLIENT_ID
    clientSecret: TIKTOK_CLIENT_SECRET
    redirectUri: TIKTOK_REDIRECT_URI
    apiVersion: TIKTOK_API_VERSION
websocket:
  namespace: 'messaging'
  transports:
  - websocket
  - polling
  allowedOrigins:
  - "*"
customChatAdapter:
  redis:
    host: redis-adapter
    port: 6379
    username: "" # Optional
    password: ${REDIS_PASSWORD} # Optional
    database: 0 # Optional - specific Redis database number
    tls: false # Optional - set to true for SSL/TLS connections
bull:
  redis:
    host: bull-redis
    port: 6379
    username: "" # Optional
    password: ${REDIS_PASSWORD} # Optional
    database: 0 # Optional - specific Redis database number
    tls: false # Optional - set to true for SSL/TLS connections
otel:
  signozIngestionKey: d95a8bd9-8eae-4695-bcd8-e07a518a3453
  region: eu
