appName: starter-template
logger:
  pinoHttp:
    level: info
    transport:
      target: 'pino-pretty'
    redact:
      paths:
        - req.headers.authorization
        - req.headers.auth
      censor: '***'
port: 3000
db:
  options:
    type: postgres
    username: root
    password: admin
    host: localhost
    port: 5432
    database: postgres
    synchronize: false
