appName: starter-template
logger:
  pinoHttp:
    level: info
    transport:
      target: 'pino-pretty'
    redact:
      paths:
        - req.headers.authorization
        - req.headers.auth
      censor: '***'
port: 3000
db:
  options:
    type: postgres
    username: root
    password: admin
    host: localhost
    port: 5432
    database: postgres
    synchronize: false
cache:
  redis:
    host: localhost
    port: 6379
    username: redisuser  # Optional
    password: redispassword  # Optional
    database: 0  # Optional - specific Redis database number
    tls: false  # Optional - set to true for SSL/TLS connections  
  defaults:
    ttl: 14400  # Default TTL in seconds (4 hours)  
  ttl:
    oauth_state: 600  # 10 minutes for OAuth states
    access_token: 3600  # 1 hour for access tokens
    refresh_token: 604800  # 7 days for refresh tokens
