appName: starter-template
logger:
  pinoHttp:
    level: info
    redact:
      paths:
        - req.headers.authorization
        - req.headers.auth
      censor: "***"
db:
  options:
    extra:
      ssl:
        rejectUnauthorized: false
