name: PR - Build / Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run Tests
        id: npmtest
        run: npm test | echo >> test_results.txt
        env:
          CI: true
          JEST_JUNIT_OUTPUT_DIR: ${{ github.workspace }}/results
          JEST_JUNIT_OUTPUT_NAME: test-results.xml

      - name: Add Test Results To Job Summary
        run: |
          echo "TEST RESULTS:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          if grep -q "FAIL" test_results.txt; then
            echo "❌ Tests failed" >> $GITHUB_STEP_SUMMARY
          else
            echo "✅ Tests passed" >> $GITHUB_STEP_SUMMARY
          fi
        if: always()

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results/**/*.xml
            test-results/**/*.trx
            test-results/**/*.json


      - name: Create test summary
        uses: test-summary/action@v2.4
        with:
          paths: ${{ github.workspace }}/results/*.xml
          output: ${{ github.workspace }}/results/summary.md
          show: "all"
        if: always()

      - name: Echo stuffs
        run: |
          cat ${{ github.workspace }}/results/test-results.xml
          cat ${{steps.npmtest.env.JEST_JUNIT_OUTPUT_DIR}}/${{steps.npmtest.env.JEST_JUNIT_OUTPUT_NAME}}
          env

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: nestjs-app
          path: dist/
          if-no-files-found: error
